version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: brcly-puffer_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"
  
  server:
    image: pufferpanel/pufferpanel:3.0.0-rc.8
    restart: on-failure
    ports:
     - 5957:5657
    volumes:
      - ${APP_DATA_DIR}/data/pufferpanel:/etc/pufferpanel
      - ${APP_DATA_DIR}/data/lib/pufferpanel:/var/lib/pufferpanel
      - ${APP_DATA_DOR}/data/run/docker.sock:/var/run/docker.sock
