version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: brcly-playit_server_1
      APP_PORT: 8008
  
  server:
    image: wisdomsky/playit-docker-web:latest
    restart: on-failure
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
