version: '3.7'

services:
  # app_proxy:
  #   environment:
  #     APP_HOST: brcly-crafty_web_1
  #     APP_PORT: 8443
  #     PROXY_AUTH_ADD: "false"
  
  server:
    container_name: brcly-crafty_server_1
    image: arcadiatechnology/crafty-4:4.4.7
    restart: on-failure
    environment:
      - TZ=Etc/UTC
    ports:
      - "8500:8000" # HTTP
      - "8543:8443"
      - "8523:8123" # DYNMAP
      - "19132:19132/udp" # BEDROCK
      - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
      - ${APP_DATA_DIR}/data/app/config:/crafty/app/config
      - ${APP_DATA_DIR}/data/logs:/crafty/logs
      - ${APP_DATA_DIR}/data/import:/crafty/import
      - ${APP_DATA_DIR}/data/backups:/crafty/backups
      - ${APP_DATA_DIR}/data/servers:/crafty/servers
